name: "Run CI"

on:
  push:
    branches: ["production"]
  pull_request:
  workflow_call:

jobs:
  test:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        task:
        - "spec"
        - "lint"
        - "metadata_lint"
        - "syntax"
        - "rubocop"
    steps:
    - uses: "actions/checkout@v4"
    - name: "rake ${{ matrix.task }}"
      run: |
        docker run --rm `docker build -q .` rake ${{ matrix.task }}
